apiVersion: v1
kind: Pod
metadata:
  name: azurediskpod1
  labels:
    servicetype: nodeportpod
  namespace: hr
spec:
  nodeName: aks-nodepool1-19553425-vmss000001
  containers:
  - name: mycontainer
    image: busybox
    args:
    - /bin/sh
    - -c
    - while true; do echo "message from pod"; echo $(myenvvar); sleep 5; done
    envFrom:
    - configMapRef:
        name: firstconfigmap
    volumeMounts:
    - name: azurediskvolume
      mountPath: /testvolume
  volumes:
  - name: azurediskvolume
    azureDisk:
      diskName: akspocdisk
      diskURI: /subscriptions/99d2f1c0-0bcf-43e7-bc9b-1147ece4d1f3/resourcegroups/MC_POC_akspoc123_westus2/providers/Microsoft.Compute/disks/akspocdisk
      kind: Managed
