apiVersion: v1
kind: Pod
metadata:
  name: hostpathpod1
  labels:
    servicetype: nodeportpod
spec:
  nodeName: aks-nodepool1-19553425-vmss000001
  containers:
  - name: mycontainer
    image: busybox
    args:
    - /bin/sh
    - -c
    - while true; do echo "message from pod"; echo $(myenvvar); sleep 5; done
    envFrom:
    - configMapRef:
        name: firstconfigmap
    volumeMounts:
    - name: myhostpath
      mountPath: /testvolume
  volumes:
  - name: myhostpath
    hostPath:
      path: /harshit
