apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    abra: dabra
spec:
  containers:
  - name: container1
    image: acrpoc123.azurecr.io/dockerimage
    ports:
    - containerPort: 80
      protocol: TCP
      name: http