apiVersion: v1
kind: Pod
metadata:
  name: secretconfigpod
  labels:
    servicetype: nodeportpod
  namespace: hr
spec:
  containers:
  - name: mycontainer
    image: busybox
    args:
    - /bin/sh
    - -c
    - while true; do echo "message from pod"; echo $(myenvvar); sleep 5; done
    env:
    - name: myenvvar
      valueFrom:
        secretKeyRef:
          key: harshit
          name: agarwal